# frozen_string_literal: true

category1 = Category.create!(name: 'Classificação', multiple_choice: false)
cat1_child1 = category1.children.create!(name: 'Compósitos')
cat1_child1.children.create!(name: 'Naturais')
cat1_child1.children.create!(name: 'Sintéticos')
cat1_child1.children.create!(name: 'Misto')
cat1_child2 = category1.children.create!(name: 'Cerâmicos')
cat1_child2.children.create!(name: 'Tradicional')
cat1_child2.children.create!(name: 'Avançado')
cat1_child2.children.create!(name: 'Revestimento')
cat1_child3 = category1.children.create!(name: 'Poliméricos')
cat1_child3_child1 = cat1_child3.children.create!(name: 'Plásticos')
cat1_child3_child1.children.create!(name: 'Naturais')
cat1_child3_child1.children.create!(name: 'Sintéticos')
cat1_child3_child2 = cat1_child3.children.create!(name: 'Fibras')
cat1_child3_child2.children.create!(name: 'Naturais')
cat1_child3_child2.children.create!(name: 'Sintéticos')
cat1_child3_child3 = cat1_child3.children.create!(name: 'Borracha')
cat1_child3_child3.children.create!(name: 'Naturais')
cat1_child3_child3.children.create!(name: 'Sintéticos')
category1_child4 = category1.children.create!(name: 'Metálicos')
category1_child4.children.create!(name: 'Ferrosos')
category1_child4.children.create!(name: 'Não Ferrosos')
category1.children.create!(name: 'Têxtil')

category2 = Category.create!(name: 'Processos de manufatura')
cat2_child1 = category2.children.create!(name: 'Fabricação digital')
cat2_child1.children.create!(name: 'Corte laser')
cat2_child1.children.create!(name: 'CNC')
cat2_child1.children.create!(name: 'Impressão 3D')
cat2_child1.children.create!(name: 'Estereolitografia (SLA)')
cat2_child1.children.create!(name: 'Outro')

cat2_child2 = category2.children.create!(
  name: 'Processos materiais poliméricos'
)
cat2_child2_child3 = cat2_child2.children.create!(name: 'Moldagem por sopro')
cat2_child2_child3.children.create!(name: 'Moldagem por extrusão')
cat2_child2_child3.children.create!(name: 'Moldagem por injeção')
cat2_child2.children.create!(name: 'Moldagem por extrusão')
cat2_child2.children.create!(name: 'Moldagem por injeção')
cat2_child2.children.create!(name: 'Moldagem por termoformação')
cat2_child2.children.create!(name: 'Rotomoldagem')
cat2_child2.children.create!(name: 'Moldagem por compressão')
cat2_child2.children.create!(name: 'Calandragem')
cat2_child2.children.create!(name: 'Imersão')

cat2_child3 = category2.children.create!(name: 'Processos materiais metálicos')
cat2_child3_child1 = cat2_child3.children.create!(name: 'Fundição')
cat2_child3_child1.children.create!(name: 'Fundição em areia')
cat2_child3_child1.children.create!(name: 'Fundição em coquilha')

cat2_child3_child5 = cat2_child3.children.create!(name: 'Estampagem')
cat2_child3_child5.children.create!(name: 'A quente')
cat2_child3_child5.children.create!(name: 'A frio')

cat2_child3_child2 = cat2_child3.children.create!(name: 'Usinagem')
cat2_child3_child2.children.create!(name: 'Furação')
cat2_child3_child2.children.create!(name: 'Usinagem molde')

cat2_child3_child3 = cat2_child3.children.create!(name: 'Corte')
cat2_child3_child3.children.create!(name: 'A água')
cat2_child3_child3.children.create!(name: 'Com serra')
cat2_child3_child3.children.create!(name: 'Com arco')

cat2_child3_child4 = cat2_child3.children.create!(name: 'União')
cat2_child3_child4.children.create!(name: 'Soldagem a ponte')
cat2_child3_child4.children.create!(name: 'Soldagem GMAW')
cat2_child3_child4.children.create!(name: 'Soldagem fricção')
cat2_child3_child4.children.create!(name: 'MIG/MAG')
cat2_child3_child4.children.create!(name: 'TIG')
cat2_child3_child4.children.create!(name: 'Adesivo')

cat2_child3.children.create!(name: 'Sinterização (metalurgia do pó)')
cat2_child3.children.create!(name: 'Laminação')

cat2_child4 = category2.children.create!(name: 'Processos materiais têxteis')
cat2_child4_child1 = cat2_child4.children.create!(name: 'Tecelagem')
cat2_child4_child1.children.create!(name: 'Tecelagem')
cat2_child4_child1.children.create!(name: 'Malharia')
cat2_child4_child1.children.create!(name: 'Não tecido')
cat2_child4_child2 = cat2_child4.children.create!(name: 'Processos primários')
cat2_child4_child2.children.create!(name: 'Desengomagem')
cat2_child4_child2.children.create!(name: 'Alvejamento')
cat2_child4_child2.children.create!(name: 'Branqueamento ótico')
cat2_child4_child2.children.create!(name: 'Navalhagem')
cat2_child4_child2.children.create!(name: 'Flambagem')
cat2_child4_child2.children.create!(name: 'Prefixação')
cat2_child4_child3 = cat2_child4.children.create!(name: 'Tingimento')
cat2_child4_child3.children.create!(name: 'Sintético')
cat2_child4_child3.children.create!(name: 'Natural')
cat2_child4_child3.children.create!(name: 'Corantes diretos')
cat2_child4_child3.children.create!(name: 'Corantes a mordente')
cat2_child4_child3.children.create!(name: 'Corantes de cuba')
cat2_child4_child3.children.create!(name: 'Corantes a cobre')
cat2_child4_child3.children.create!(name: 'Corante ácido')
cat2_child4_child4 = cat2_child4.children.create!(name: 'Costura')
cat2_child4_child4.children.create!(name: 'Reta')
cat2_child4_child4.children.create!(name: 'Zig-zag')
cat2_child4_child4.children.create!(name: 'Overloque')
cat2_child4_child4.children.create!(name: 'Interloque')

cat2_child4_child5 = cat2_child4.children.create!(name: 'Fiação')
cat2_child4_child5.children.create!(name: 'Anel')
cat2_child4_child5.children.create!(name: 'Rotor')
cat2_child4_child6 = cat2_child4.children.create!(name: 'União')
cat2_child4_child6.children.create!(name: 'Por adesivo')
cat2_child4_child6.children.create!(name: 'Por solda')
cat2_child4_child7 = cat2_child4.children.create!(name: 'Estamparia')
cat2_child4_child7.children.create!(name: 'Batik')
cat2_child4_child7.children.create!(name: 'Bloco de Madeira')
cat2_child4_child7.children.create!(name: 'Rolo de Madeira')
cat2_child4_child7.children.create!(name: 'Cilindro')
cat2_child4_child7.children.create!(name: 'Silk')
cat2_child4_child7.children.create!(name: 'Cilindro Rotativo')
cat2_child4_child7.children.create!(name: 'Transfer')
cat2_child4_child7.children.create!(name: 'Estamparia Digital')
cat2_child4_child7.children.create!(name: 'Bordagem')

cat2_child4_cd8 = cat2_child4.children.create!(name: 'Demais beneficiamentos')
cat2_cd4_cd8_cd1 = cat2_child4_cd8.children.create!(name: 'Resinagem')
cat2_cd4_cd8_cd1.children.create!(name: 'PVC')
cat2_cd4_cd8_cd1.children.create!(name: 'Acrílica')
cat2_cd4_cd8_cd1.children.create!(name: 'Termofixagem')
cat2_child4_cd8.children.create!(name: 'Crackant')
cat2_child4_cd8.children.create!(name: 'Wash and wear')
cat2_child4_cd8.children.create!(name: 'Antifogo')
cat2_child4_cd8.children.create!(name: 'Antimanchas')
cat2_child4_cd8.children.create!(name: 'Antiestáticos')
cat2_child4_cd8.children.create!(name: 'Anti Microorganismos')
cat2_child4_cd8.children.create!(name: 'Anti parasitas')
cat2_child4_cd8.children.create!(name: 'Antirruga')
cat2_child4_cd8.children.create!(name: 'Aplicação de amaciantes')
cat2_child4_cd8.children.create!(name: 'Aplicação de encorpantes')
cat2_child4_cd8.children.create!(name: 'Calandragem')
cat2_child4_cd8.children.create!(name: 'Carregamento')
cat2_child4_cd8.children.create!(name: 'Escovagem')
cat2_child4_cd8.children.create!(name: 'Flanelagem')
cat2_child4_cd8.children.create!(name: 'Gofragem')
cat2_child4_cd8.children.create!(name: 'Hidrofugação')
cat2_child4_cd8.children.create!(name: 'Impermeabilização')
cat2_child4_cd8.children.create!(name: 'Lixagem')
cat2_child4_cd8.children.create!(name: 'Moiré')
cat2_child4_cd8.children.create!(name: 'Pré-encolhimento')
cat2_child4_cd8.children.create!(name: 'Prensagem permanente')

cat2_cd5 = category2.children.create!(name: 'Processos de materiais cerâmicos')
cat2_cd5.children.create!(name: 'Prensagem')
cat2_cd5.children.create!(name: 'Moldagem em barbotina (slip casting)')
cat2_cd5.children.create!(name: 'Moldagem em fita (tape casting)')
cat2_cd5.children.create!(name: 'Conformação plástica')
cat2_cd5.children.create!(name: 'Moldagem por injeção')

category3 = Category.create!(name: 'Superfície', multiple_choice: false)
category3.children.create!(name: 'Lisa')
category3.children.create!(name: 'Texturizada')
category3.children.create!(name: 'Outro')

category4 = Category.create!(name: 'Aspecto visual', multiple_choice: false)
category4.children.create!(name: 'Brilhoso')
category4.children.create!(name: 'Opaco')
category4.children.create!(name: 'Reflexivo')
category4.children.create!(name: 'Translúcido')
category4.children.create!(name: 'Semi-translúcido')
category4.children.create!(name: 'Outro')

category5 = Category.create!(name: 'Maleabilidade', multiple_choice: false)
category5.children.create!(name: 'Rígido')
category5.children.create!(name: 'Flexível')
category5.children.create!(name: 'Semi-flexível')
category5.children.create!(name: 'Outro')

category6 = Category.create!(name: 'Aplicação por indústria')
cat6_child2 = category6.children.create!(name: 'Indústria da construção civil')
cat6_child2.children.create!(name: 'Urbanismo')
cat6_child2.children.create!(name: 'Arquitetura')
cat6_child2.children.create!(name: 'Decoração')
category6.children.create!(name: 'Indústria da moda')
category6.children.create!(name: 'Indústria automotiva')
category6.children.create!(name: 'Indústria gráfica')
category6.children.create!(name: 'Indústria alimentícia')
category6.children.create!(name: 'Indústria de embalagem')
category6.children.create!(name: 'Indústria de eletroeletrônicos')
category6.children.create!(name: 'Indústria de beleza')
category6.children.create!(name: 'Outros')

category7 = Category.create!(name: 'Aplicação por funcionalidade')
cat7_child1 = category7.children.create!(name: 'Acabamentos')
cat7_child1.children.create!(name: 'Tinta')
cat7_child1.children.create!(name: 'Verniz')
cat7_child1.children.create!(name: 'Impermeabilizante')
cat7_child2 = category7.children.create!(name: 'Revestimento')
cat7_child2.children.create!(name: 'Para fachada interna')
cat7_child2.children.create!(name: 'Para fachada externa')
cat7_child5 = category7.children.create!(name: 'Isolamento e preenchimento')
cat7_child5.children.create!(name: 'Acústico')
cat7_child5.children.create!(name: 'Térmico')
cat7_child5.children.create!(name: 'Preenchimento')
cat7_child11 = category7.children.create!(name: 'Piso')
cat7_child11.children.create!(name: 'Piso interno')
cat7_child11.children.create!(name: 'Piso externo')
category7.children.create!(name: 'Estrutural')
category7.children.create!(name: 'Adesivo')
category7.children.create!(name: 'Têxtil')
category7.children.create!(name: 'Mobiliário')
category7.children.create!(name: 'Decoração')
category7.children.create!(name: 'Iluminação')
category7.children.create!(name: 'Preenchimento')
category7.children.create!(name: 'Brinquedos infantis')
category7.children.create!(name: 'Outro')
